# Simpleapp NodePort Service
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
  labels:
    app: simpleapp-app
spec:
  selector:
    app: simpleapp-app
  type: NodePort
  ports:
  - nodePort: 32100
    port: 8080
    targetPort: 8080
---
#  Simpleapp Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deploy
spec:
  selector:
    matchLabels:
      app: simpleapp-app
  replicas: 2
  template:
    metadata:
      labels:
        app: simpleapp-app
    spec:
      containers:
        - name: simpleapp
          image: bathurudocker/simpleapp:latest
          ports:
            - containerPort: 8080
