#simpleapp
---
apiVersion: v1
kind: Namespace
metadata:
  name: prodNS
  labels:
    app: simpleapp-app
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
  namespace: prodNS
  labels:
    app: simpleapp-app
spec:
  selector:
    app: simpleapp-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp-deploy
spec:
  selector:
    matchLabels:
      app: simpleapp-app
  replicas: 1
  template:
    metadata:
      name: my-deployment
      namespace: prodNS
      labels:
        app: simpleapp-app
    spec:
      containers:
        - name: simpleapp
          image: sbathuru/devops-simpleapp:latest
          ports:
            - containerPort: 8080
#  http://3.6.94.232:32000/simpleapp/

