#simpleapp
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
  namespace: { { .Values.namespace } }
  labels:
    app: simpleapp-app
spec:
  selector:
    app: simpleapp-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
